nginx:
  image: fumblesandfriends/nginx
  links:
    - node1:node1
    - node2:node2
    - blog1:blog1
  ports:
    - "80:80"
node1:
  image: fumblesandfriends/node
  ports:
    - "8080"
  volumes:
    - node:/src
  environment:
    - RACK_ENV=production
node2:
  build: fumblesandfriends/node
  ports:
    - "8080"
  volumes:
    - node:/src
  environment:
    - RACK_ENV=production
blog1:
  image: dockerfile/ghost
  ports:
    - "2368"
  volumes:
    - blog:/ghost-override
